### PR TITLE
[Security fix] update to v8.0.7 + chg, use direct url not repo

### PR DESCRIPTION
**Pull request by nathanael-h**
## Problem

- Security issue in v8.0.6 cf issue #38 

## Solution

- Update to v8.0.7
- As this version is not available is repo anymore we have to use direct URL to deb file

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by nathanael-h** [comment]
!testme

**Comment by ericgaspar** [comment]
!tastemetitus

**Comment by nathanael-h** [comment]
!testme

**Comment by JimboJoe** [comment]
Thanks for your contribution!
I've (at last) opened #41 to upgrade to 8.3.3 and fix the restoration bug, thus not changing the package retrieval mechanism.

**Comment by nathanael-h** [comment]
Ah thank you 👍

**Pull request closed without merging**
