### PR TITLE
Upgrade to upstream version 7.5.5

### PR DESCRIPTION
**Pull request by JimboJoe**

### CODE REVIEW

**Comment by JimboJoe** [comment]
!testme

**Comment by JimboJoe** [comment]
!testme

**Comment by JimboJoe** [comment]
!testme

**Review by alexAubin — APPROVED** [review]
Quick review, LGTM

**Comment by JimboJoe** [comment]
!testme

**Comment by JimboJoe** [comment]
Suggested edit:
```diff
diff --git a/scripts/restore b/scripts/restore
index b8af5ca..3294352 100644
--- a/scripts/restore
+++ b/scripts/restore
@@ -29,6 +29,7 @@ app=$YNH_APP_INSTANCE_NAME
 
 domain=$(ynh_app_setting_get --app=$app --key=domain)
 path_url=$(ynh_app_setting_get --app=$app --key=path)
+final_path=$(ynh_app_setting_get --app=$app --key=final_path)
 db_name=$(ynh_app_setting_get --app=$app --key=db_name)
 db_user=$db_name
 

```

**Pull request merged**
