### PR TITLE
Update influxdb to v2 (influxdb2)

### PR DESCRIPTION
**Pull request by biva**
## Problem
Current version of InfluxDB includes the official Debian repository, which is not updated for a long time (probably 2018 or 2019): 

- Potential security issues as the Debian repository is not really maintained (https://github.com/influxdata/influxdb/issues/10638#issuecomment-1031550651)
- The upgrade from 1.x to 2.1 looks not that easy, and it will be required at some point in the future, when 1.x won’t be maintained anymore: better to start with v2 from the beginning
- the flux language looks like the future of Influx DB, more powerful: I’d like to start writing our queries with this, rather than changing everything in the future
- It includes basic dashboards (I could avoid Grafana for some easy monitoring)
- It includes an alert system (in case of data collection has an issue for instance)

## Solution

Move to influxdb2, using the repository of InfluxData

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)
- [ ] Additional integrations (notably netdata) are disabled for now to keep it simple

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by biva** [comment]
I'm not sure if we should also include the dependency for the CLI, which is now a separate package:

`pkg_dependencies="influxdb2-cli"`

Or if, as a first draft version, we can ask the user to setup Influxdb with the UI?

- With InfluxDB running, visit http://yourserver.com:8086
- Click _Get Started_

**Comment by biva** [comment]
I also created another PR to modify the install process: https://github.com/YunoHost-Apps/grafana_ynh/pull/46
This one is much more complex for me and requires support :/

**Comment by biva** [comment]
Hello @JimboJoe , following our initial conversation in https://forum.yunohost.org/t/influxdb-version-in-grafana-update-to-v2/18685, would you be available to help me on this PR and https://github.com/YunoHost-Apps/grafana_ynh/pull/46 ?

**Comment by biva** [comment]
Hello @JimboJoe @yalh76 What do you think about this idea to update to InfluxDB 2? Would you be able to have a look?
Thank you in advance! 🤗

**Comment by biva** [comment]
Hello @JimboJoe @yalh76 @ericgaspar 
I still think it would be a good idea to update to v2: it would be safer for the users (Debian repository is not maintained), follow the recommendations of InfluxDB, and offer additional features.
Would you have some time to look at the PR that I proposed?
Thanks for your support!

**Comment by ericgaspar** [comment]
!testme

**Comment by biva** [comment]
Thank you @ericgaspar , I see that the issue is about the package influxdb2, which is not available. I guess it's because the repository is not known? I added the repository in https://github.com/YunoHost-Apps/grafana_ynh/pull/46/commits/3a84b9824144a88968616ad150a52a1f61155845 but I'm not sure how to add it in this file as well?

**Comment by JimboJoe** [comment]
Hello,
Sorry for not answering back more promptly...
As you have already seen, I have very minimal time to spend on this. I've just updated the app to the latest grafana version and fixed the initial configuration for first installations.
As for the end of maintenance of the Debian InfluxDB repository, thanks for pointing that out.
As you've already seen, the [InfluxDB V1->V2 migration](https://docs.influxdata.com/influxdb/v2.4/upgrade/v1-to-v2/automatic-upgrade/) procedure is far from trivial and would require quite some hours to automatize in this package.
But as such, and for the use case of this package (provide a storing and long-term dashboard capability to NetData), I don't see any urgency, provided InfluxDB is kept as an internal database and not exposed externally.
I'll see in the future if I find some time for see, but really I can't promise anything...

**Comment by biva** [comment]
Hello @JimboJoe ,
Thanks for your feedback and I fully understand. Regarding the initial configuration for first installations, does it mean that it will install InfluxDB2 if I install the package today, in a fresh install? Will it use the InfluxDB repository and not the Debian one?
If not, would it require a lot of work to enable that just for a new installation, and work on the migration later?

**Comment by JimboJoe** [comment]
No, it will stay with version 1 from Debian. Maintaining potentially 2 user bases with sensibly different versions is something I just can't afford. But please step up if you feel like you can make it.

**Pull request closed without merging**
