### PR TITLE
Choice port during install

### PR DESCRIPTION
**Pull request by nemsia**
I wan't to use this package with mastodon and they use the same port (3000).

I propose to choice the port on installation.

### CODE REVIEW

**Comment by JimboJoe** [comment]
Hi @nemsia,
Thanks a lot for your PR!
Did you test the package with package_check?
Can you possibly update the check_process file as well to test specified port usage (as in this [example](https://github.com/YunoHost/package_check/blob/master/check_process#L11) lines 11 and 23)?

I also invited you to the YunoHost-Apps organization: so if you ask to work on packages, we'll give you rights and you'll be able to commit directly to YunoHost-Apps repositories and we can work together on a PR ;-)

**Comment by nemsia** [comment]
I will add the port test to check_process.
I have just started working on the mastodon_ynh package with cyp and I am very bad, lots of errors and commits to nothing;), I learn to better and soon why not, but it is a bit earlier in my opinion.

**Comment by nemsia** [comment]
OK, i accept.

**Comment by JimboJoe** [comment]
@nemsia, sorry if I was not clear: I was talking about the **GitHub** YunoHost-Apps organization: we invite systematically every YunoHost package to join this organization to be able to maintain the package in the future if the packager can't any more (without forking) and to be able to work together.
If you were referring to the YunoHost Apps Group (which cyp joined recently), of course it's too early for you, but if you like YunoHost packaging and get more experience, we'll think about it in the future: I think we will never be too many to manage the project ^^

**Comment by JimboJoe** [comment]
@nemsia can you possibly embed [this helper](https://github.com/YunoHost/yunohost/blob/unstable/data/helpers.d/network#L25-L39) (not in YunoHost stable yet) and check for the port availability like in [this example](https://github.com/YunoHost-Apps/lutim_ynh/blob/master/scripts/install#L54)?

**Comment by nemsia** [comment]
It work well.

**Comment by JimboJoe** [comment]
Passes the new **real** port test from package_check ! 👍 
Thanks again ;-)

**Pull request merged**
