### PR TITLE
Backup all databases and use portable format

### PR DESCRIPTION
**Pull request by BrunoSpy**
Portable format is recommended by influxdata for version > 1.4

## Problem

#95 

## Solution

- *And how do you fix that problem*

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by BrunoSpy** [comment]
!testme

**Comment by JimboJoe** [comment]
Source for recommendation to move to portable format [here](https://docs.influxdata.com/influxdb/v1.8/administration/backup_and_restore/#we-recommend-the-portable-format).
Should we really backup all databases beyond the one that is created/used for grafana...?

**Comment by JimboJoe** [comment]
!testme

**Comment by BrunoSpy** [comment]
> Should we really backup all databases beyond the one that is created/used for grafana...?

That's what I expected. If not, it should be explained with a warning in the README.

**Comment by JimboJoe** [comment]
Just tried a manual test, and the restoration failed, particularly with the influxdb restoration:
```
2023-05-05 16:41:43,354 DEBUG    yunohost.hook (unknown function) - [180178.1] + influxd restore -portable ./influxdb_data
2023-05-05 16:41:43,369 WARNING  yunohost.hook (unknown function) - [180178.1] 2023/05/05 16:41:43 error updating meta: dial tcp 127.0.0.1:8088: connect: connection refused
2023-05-05 16:41:43,371 WARNING  yunohost.hook (unknown function) - [180178.1] restore: dial tcp 127.0.0.1:8088: connect: connection refused
```

Was it working on your side?

**Pull request merged**
